LIB_SRCS_C   = 	main.c  \
		utility.c  \
		led.c \
		system_state.c \
		json.c \
		applied_math.c \
		fifo.c \
		circular_queue.c \
		hard_ware.c \
		relay.c \
		watch_dog.c \
		gprs.c \
		socket.c \
		gsm.c \
		sms.c \
		uart.c \
		g_sensor.c \
		nmea_protocol.c \
		gps.c \
		log_service.c \
		gps_service.c \
		gps_save.c \
		agps_service.c \
		config_save.c \
		config_service.c \
		update_file.c \
		update_service.c \
		protocol.c \
		protocol_goome.c \
		protocol_jt808.c \
		command.c \
		auto_test.c\
		bms.c \
		
